### ISSUE TITLE
Request for partition stability code for proteins

### ISSUE THREAD

**Issue by rakeshr10** [michaelschaub/PartitionStability#3]
Hi,

Can you share the partition stability code for proteins which was published in Physical biology as well as in Molecular Biosystems.

Regards
Rakesh

**Comment by michaelschaub** [comment]
Dear Rakesh,

I am not sure I understand your request. The repository contains the
code for Partition Stability.
Or are you referring to another part of the analysis in the publications
you mention? Feel free to send me an Email.

Michael

**Comment by BIORAK** [comment]
Hi,
   
   Yes I am looking for the set of codes or examples for the analysis which have been performed in the publications for proteins like the allosteric pathways in caspase-1 or the adenylate kinase etc. Specifically the Markov stability in the atomistic graph representation of proteins.

Regards
Rakesh

**Comment by michaelschaub** [comment]
As for the Markov Stability part, there is the data for the graph for of
adenylate kinase included in the demo folder, as you have surely seen.

How to construct the graph from a protein, however, is a different
matter that is distinct from this and not covered within this
repository. I suggest you get in contact with the authors from the
respective papers (my former colleagues at Imperial).

cheers,

Michael

**Comment by BIORAK** [comment]
Thanks for the information. I will contact the respective authors.

Regards
Rakesh
